### ISSUE TITLE
--split-x cannot be used when the dataset already contains an XY region

### ISSUE THREAD

**Issue by jessica-agnewblais** [JoniColeman/gwas_scripts#8]
Hi,

I am attempting to do some QC, but when I get to the code for doing the sex check and I run: 

plink \
--bfile $root.LD_two \
--split-x b38 \
--make-bed \
--out $root.LD_split

I get the error:

Warning: 1918 het. haploid genotypes present (see
/users/k1469373/brc_scratch/pelotas/from_hamel/final_zcall/Brazil_Pelotas_GSAMDv2_intensity_data_zcall_final.LD_split.hh); many commands treat these as missing.
Warning: Nonmissing nonmale Y chromosome genotype(s) present; many commands treat these as missing.
Total genotyping rate is 0.999403.
285784 variants and 997 people pass filters and QC.
Among remaining phenotypes, 694 are cases and 286 are controls.  (17 phenotypes are missing.)
Error: --split-x cannot be used when the dataset already contains an XY region.

Sorry, I am very new to Plink and I'm a bit worried if I try to fix this willy-nilly on my own I will mess something up without realizing it! If you have any advice it would be much appreciated.

Thanks!
Jess

**Comment by JoniColeman** [comment]
This is fine - --split-X is not necessary to run on your data, because it already contains a separate XY region (some older chips have this paralogous region included with the rest of the X data). You can just skip this flag and move to the next.

**Comment by jessica-agnewblais** [comment]
phew! thanks!!
________________________________
